function ManagementReportTab({ funds, requests, disbursements, liquidations, replenishments, auditLog, plantTitle, generatedBy }) {
  const [type, setType] = useState("CASHPOS");
  const [F, setF] = useState({ from: "", to: "", company: "", plant: "", branch: "", custodian: "", status: "", category: "", account: "" });
  const [watermark, setWatermark] = useState(false);
  const [orientation, setOrientation] = useState("");
  const set = (k, v) => setF((s) => ({ ...s, [k]: v }));

  const def = REPORT_TYPES.find((r) => r.code === type) || REPORT_TYPES[0];
  const D = useMemo(
    () => ({ funds, requests, disbursements, liquidations, replenishments, auditLog: auditLog || [] }),
    [funds, requests, disbursements, liquidations, replenishments, auditLog]
  );
  const built = useMemo(() => buildReport(type, D, F), [type, D, F]);
  const ort = orientation || def.orientation;

  const plantOpts = useMemo(() => {
    const seen = new Map();
    funds.forEach((f) => { if (!seen.has(f.branchCode)) seen.set(f.branchCode, f.label || plantLabel(f.branchCode)); });
    return [...seen.entries()].map(([code, label]) => ({ code, label }));
  }, [funds]);
  const custodianOpts = useMemo(() => [...new Set(funds.map((f) => f.custodian).filter(Boolean))], [funds]);
  const accountOpts = useMemo(() => [...new Set(Object.values(EXPENSE_CATEGORY_ACCOUNTS))].sort(), []);
  const branchOpts = useMemo(() => (F.company ? branchesForCompany(F.company) : BRANCHES), [F.company]);
  const statusOpts = useMemo(() => {
    if (type === "REPL") return REPLENISH_STATUSES;
    if (type === "DISB" || type === "OUT") return ["Not Liquidated", "Partially Liquidated", "Fully Liquidated", "Over-Liquidated"];
    return [];
  }, [type]);

  /* The company a report belongs to, inferred from the active scope: an explicit
     company/branch/plant filter wins; otherwise, if every fund in scope shares
     one company (e.g. Manila -> A1+), use that. Empty = mixed (all plants). */
  const scopeCompany = useMemo(() => {
    if (F.company) return F.company;
    if (F.branch) return companyOfBranch(F.branch);
    if (F.plant) return companyOfBranch(F.plant);
    const companies = [...new Set(funds.map((f) => companyOfBranch(f.branchCode)).filter(Boolean))];
    return companies.length === 1 ? companies[0] : "";
  }, [F.company, F.branch, F.plant, funds]);

  const meta = useMemo(() => {
    const custodianFromPlant = F.plant ? ((funds.find((f) => f.branchCode === F.plant) || {}).custodian || "") : "";
    const period = (F.from || F.to)
      ? `${F.from ? fmtDate(F.from) : "Beginning"} to ${F.to ? fmtDate(F.to) : fmtDate(todayISO())}`
      : "All Dates";
    return {
      "Plant": F.plant ? plantLabel(F.plant) : (plantTitle || "All Plants"),
      "Branch": F.branch || (F.plant || "All Branches"),
      "Company": F.company || scopeCompany || "All Companies",
      "Custodian": F.custodian || custodianFromPlant || "All Custodians",
      "Report Period": period,
      "Generated By": generatedBy || "System",
      "Date Generated": nowStamp(),
    };
  }, [F, plantTitle, generatedBy, funds, scopeCompany]);

  const reference = useMemo(() => makeReportRef(def.code), [def.code, F, type]);

  const doc = useMemo(() => ({
    title: def.label, orientation: ort, columns: built.columns, rows: built.rows,
    totalsRow: built.totalsRow, count: built.count, meta, reference, watermark,
    company: scopeCompany, logo: logoForCompany(scopeCompany),
  }), [def.label, ort, built, meta, reference, watermark, scopeCompany]);

  const resetFilters = () => setF({ from: "", to: "", company: "", plant: "", branch: "", custodian: "", status: "", category: "", account: "" });

  const cell = (row, col) => {
    const v = row[col.key];
    if (col.money) return (v == null || v === "") ? "" : money(v);
    return v == null ? "" : v;
  };

  return (
    <div>
      <TopBar
        title={(plantTitle ? plantTitle + " \u00b7 " : "") + "Report Center"}
        sub="Professional, print-ready reports — A4, PDF, Excel and CSV"
        right={
          <>
            <button className="pcp-btn" onClick={() => printReportDocument(doc)}><Printer size={14} /> Print</button>
            <button className="pcp-btn" onClick={() => printReportDocument(doc)}><FileText size={14} /> Save as PDF</button>
            <button className="pcp-btn" onClick={() => exportReportExcel(doc)}><FileSpreadsheet size={14} /> Excel</button>
            <button className="pcp-btn pcp-btn-primary" onClick={() => exportReportCsv(doc)}><Download size={14} /> CSV</button>
          </>
        }
      />
      <div className="pcp-content">
        {/* ---- Controls: report type, filters, options ---- */}
        <div className="pcp-card pcp-card-pad pcp-no-print" style={{ marginBottom: 16 }}>
          <div className="pcp-rc-filters" style={{ marginBottom: 12 }}>
            <div className="pcp-rc-field" style={{ gridColumn: "span 2" }}>
              <label>Report</label>
              <select className="pcp-select" value={type} onChange={(e) => setType(e.target.value)}>
                {REPORT_TYPES.map((r) => <option key={r.code} value={r.code}>{r.label}</option>)}
              </select>
            </div>
            <div className="pcp-rc-field">
              <label>Date From</label>
              <input type="date" className="pcp-input" value={F.from} onChange={(e) => set("from", e.target.value)} />
            </div>
            <div className="pcp-rc-field">
              <label>Date To</label>
              <input type="date" className="pcp-input" value={F.to} onChange={(e) => set("to", e.target.value)} />
            </div>
          </div>
          <div className="pcp-rc-filters">
            <div className="pcp-rc-field">
              <label>Company</label>
              <select className="pcp-select" value={F.company} onChange={(e) => { set("company", e.target.value); set("branch", ""); }}>
                <option value="">All Companies</option>
                {COMPANIES.map((c2) => <option key={c2} value={c2}>{c2}</option>)}
              </select>
            </div>
            <div className="pcp-rc-field">
              <label>Plant</label>
              <select className="pcp-select" value={F.plant} onChange={(e) => set("plant", e.target.value)}>
                <option value="">All Plants</option>
                {plantOpts.map((p) => <option key={p.code} value={p.code}>{p.label}</option>)}
              </select>
            </div>
            <div className="pcp-rc-field">
              <label>Branch</label>
              <select className="pcp-select" value={F.branch} onChange={(e) => set("branch", e.target.value)}>
                <option value="">All Branches</option>
                {branchOpts.map((b) => <option key={b.code} value={b.code}>{b.name} ({b.code})</option>)}
              </select>
            </div>
            <div className="pcp-rc-field">
              <label>Custodian</label>
              <select className="pcp-select" value={F.custodian} onChange={(e) => set("custodian", e.target.value)}>
                <option value="">All Custodians</option>
                {custodianOpts.map((c2) => <option key={c2} value={c2}>{c2}</option>)}
              </select>
            </div>
            <div className="pcp-rc-field">
              <label>Status</label>
              <select className="pcp-select" value={F.status} onChange={(e) => set("status", e.target.value)} disabled={!statusOpts.length}>
                <option value="">{statusOpts.length ? "All Statuses" : "Not applicable"}</option>
                {statusOpts.map((s) => <option key={s} value={s}>{s}</option>)}
              </select>
            </div>
            <div className="pcp-rc-field">
              <label>Expense Category</label>
              <select className="pcp-select" value={F.category} onChange={(e) => set("category", e.target.value)}>
                <option value="">All Categories</option>
                {EXPENSE_CATEGORIES.map((c2) => <option key={c2} value={c2}>{c2}</option>)}
              </select>
            </div>
            <div className="pcp-rc-field">
              <label>Chart of Account</label>
              <select className="pcp-select" value={F.account} onChange={(e) => set("account", e.target.value)}>
                <option value="">All Accounts</option>
                {accountOpts.map((a) => <option key={a} value={a}>{a}</option>)}
              </select>
            </div>
            <div className="pcp-rc-field">
              <label>Orientation</label>
              <select className="pcp-select" value={orientation} onChange={(e) => setOrientation(e.target.value)}>
                <option value="">Auto ({def.orientation})</option>
                <option value="portrait">Portrait</option>
                <option value="landscape">Landscape</option>
              </select>
            </div>
          </div>
          <div style={{ display: "flex", alignItems: "center", gap: 18, marginTop: 14, flexWrap: "wrap" }}>
            <label style={{ display: "flex", alignItems: "center", gap: 7, fontSize: 12.5, fontWeight: 600, cursor: "pointer" }}>
              <input type="checkbox" checked={watermark} onChange={(e) => setWatermark(e.target.checked)} />
              CONFIDENTIAL watermark
            </label>
            <span style={{ fontSize: 12, color: "var(--text-mut)" }}>Reference No.: <b style={{ color: "var(--text)" }}>{reference}</b></span>
            <button className="pcp-btn pcp-btn-sm" style={{ marginLeft: "auto" }} onClick={resetFilters}>Reset Filters</button>
          </div>
        </div>

        {/* ---- On-screen A4 paper preview (mirrors print / PDF) ---- */}
        <div className="pcp-doc-scroll">
          <div className={"pcp-doc " + ort}>
            {watermark && <div className="pcp-doc-wm"><span>CONFIDENTIAL</span></div>}
            <div className="pcp-doc-head">
              <img src={doc.logo} alt="Company logo" />
              <div className="pcp-doc-head-c">
                <div className="pcp-doc-company">{companyHeaderName(scopeCompany)}</div>
                <div className="pcp-doc-portal">{PORTAL_NAME}</div>
                <div className="pcp-doc-title">{def.label}</div>
              </div>
              <div className="pcp-doc-ref"><b>Ref: {reference}</b><div>Verification No.</div></div>
            </div>
            <div className="pcp-doc-meta">
              {Object.entries(meta).map(([k, v]) => <div key={k}><b>{k}:</b> {v}</div>)}
            </div>
            <div className="pcp-doc-count">Transaction Count: {built.count}</div>
            <table className="pcp-doc-table">
              <thead>
                <tr>{built.columns.map((col) => <th key={col.key} className={"a-" + col.align}>{col.label}</th>)}</tr>
              </thead>
              <tbody>
                {built.rows.length === 0 && (
                  <tr><td colSpan={built.columns.length} style={{ textAlign: "center", padding: 18, color: "#888" }}>No records for the selected filters.</td></tr>
                )}
                {built.rows.map((row, i) => (
                  row._group
                    ? <tr key={i} className="grp"><td colSpan={built.columns.length}>{row.particulars || row[built.columns[0].key]}</td></tr>
                    : <tr key={i} className={row._subtotal ? "sub" : ""}>{built.columns.map((col) => <td key={col.key} className={"a-" + col.align}>{cell(row, col)}</td>)}</tr>
                ))}
                <tr className="nf"><td colSpan={built.columns.length}>———  NOTHING FOLLOWS  ———</td></tr>
                {built.totalsRow && <tr className="tot">{built.columns.map((col) => <td key={col.key} className={"a-" + col.align}>{cell(built.totalsRow, col)}</td>)}</tr>}
              </tbody>
            </table>
            <div className="pcp-doc-foot">
              <span>Generated from PCF Portal · {PORTAL_NAME}</span>
              <span>Printed on: {nowStamp()} · Page 1 of 1</span>
            </div>
            <div className="pcp-doc-sign">
              <div className="box"><div className="who">Prepared by:</div><div className="line">{meta.Custodian}</div><div className="role">Custodian</div></div>
              <div className="box"><div className="who">Reviewed by:</div><div className="line">&nbsp;</div><div className="role">Accounting Manager</div></div>
              <div className="box"><div className="who">Approved by:</div><div className="line">&nbsp;</div><div className="role">Finance Director</div></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
